name: publish 
on:
  push:
    branches: 
      - main
    paths:
      - docs/**
      - mkdocs.yml
      - requirements-docs.txt
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements-docs.txt
      - run: mkdocs gh-deploy --force
